CREATE TABLE IF NOT EXISTS dinner_plans (
  identity_hash TEXT PRIMARY KEY,
  plan JSONB NOT NULL,
  revision BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
